### ISSUE TITLE
tool_calling_via_callback/st_callable_util.py => displays sub-agent responses 

### ISSUE THREAD

**Issue by nick-youngblut** [shiv248/Streamlit-x-LangGraph-Cookbooks#2]
[st_callable_util.py](https://github.com/shiv248/Streamlit-x-LangGraph-Cookbooks/blob/master/tool_calling_via_callback/st_callable_util.py) will stream the sub-agent responses to the supervisor agent, in addition to the final response, which looks messy/confusing.

This is at least true if the sub-agent is set up to respond with a `HumanMessage` object:

```python
def create_agent_node(state, agent, name):
    result = agent.invoke(state)
    return {"messages": [HumanMessage(content=result["output"], name=name)]}
```

**Comment by shiv248** [comment]
hey @nick-youngblut thanks for bringing up this issue, I'll take some time and check it out.

do you have a minimal reproducible graph you could share where you face this issue?
I'm assuming you're referring to subgraphs like [this](https://langchain-ai.github.io/langgraph/how-tos/subgraph/) LangGraph guide or [this](https://langchain-ai.github.io/langgraph/tutorials/multi_agent/hierarchical_agent_teams/) supervisor - agent graph?

**Comment by nick-youngblut** [comment]
Thanks @shiv248 for the quick response! 
My graph architecture is similar to https://langchain-ai.github.io/langgraph/tutorials/multi_agent/hierarchical_agent_teams/, but the supervisor can respond with `FINISH`, which calls a final `summary` chain to provide a final answer to the user.

I don't have a full minimal example right now, but the basic code is as follows:

```python
# The agent state is the input to each node in the graph
class AgentState(TypedDict):
    # The annotation tells the graph that new messages will always
    messages: Annotated[Sequence[BaseMessage], operator.add]
    # The 'next' field indicates where to route to next
    next: str

def create_workflow(llm, members):
    # Agent1
    agent1 = create_agent(llm, get_agent1_tools(), "You may call the XX API")
    agent1_node = functools.partial(create_agent_node, agent=agent1, name="Agent1")

    # Agent2
    agent2 = create_agent(llm, get_agent2_tools(), "You may call the YY API")
    agent2_node = functools.partial(create_agent_node, agent=agent2, name=Agent2")

    # Create the workflow
    workflow = StateGraph(AgentState)
    workflow.add_node("Agent1", agent1_node)
    workflow.add_node("Agent2", agent2_node)
    workflow.add_node("Supervisor", create_supervisor_chain(llm, members))
    workflow.add_node("Summary", summary_generator)

    # Report back to supervisor
    for member in members:
        # We want our workers to ALWAYS "report back"
        workflow.add_edge(member, "Supervisor")

    # The supervisor populates the "next" field in the graph state
    # which routes to a node or finishes
    conditional_map = {k: k for k in members}
    conditional_map["FINISH"] = "Summary"
    workflow.add_conditional_edges("Supervisor", lambda x: x["next"], conditional_map)
    # Finally, add entrypoint
    workflow.add_edge(START, "Supervisor")
    workflow.add_edge("Summary", END)

    # Return the workflow
    return workflow

def create_agent(llm: ChatOpenAI, tools: list, system_prompt: str, name: str="agent"):
    # Each worker node will be given a name and some tools.
    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                system_prompt,
            ),
            MessagesPlaceholder(variable_name="messages"),
            MessagesPlaceholder(variable_name="agent_scratchpad"),
        ]
    )
    agent = create_openai_tools_agent(llm, tools, prompt)
    executor = AgentExecutor(agent=agent, tools=tools)
    executor.name = name
    return executor

def create_agent_node(state, agent, name):
    result = agent.invoke(state, callbacks=[])
    return {"messages": [HumanMessage(content=result["output"], name=name)]}

def create_supervisor_chain(llm, members):
    """
    Create a supervisor chain that routes the conversation to the next worker in the list.
    """
    # Set the system prompt for the supervisor
    system_prompt = (
        "You are a supervisor tasked with managing a conversation between the following workers: {members}."
        " Given the following user request, respond with the worker to act next."
        " Each selected worker will perform a task and respond with their results and status."
        " When finished, respond with FINISH."
        " Only some workers may be needed to complete the task. You do not need to use all workers."
    )
    # Our team supervisor is an LLM node. 
    ## It just picks the next agent to process and decides when the work is completed
    options = ["FINISH"] + members
    # Using openai function calling can make output parsing easier for us
    function_def = {
        "name": "route",
        "description": "Select the next role.",
        "parameters": {
            "title": "routeSchema",
            "type": "object",
            "properties": {
                "next": {
                    "title": "Next",
                    "anyOf": [
                        {"enum": options},
                    ],
                }
            },
            "required": ["next"],
        },
    }
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", system_prompt),
            MessagesPlaceholder(variable_name="messages"),
            (
                "system",
                "Given the conversation above, should we FINISH, or which worker should act next?"
                " Select one of: {options}",
            ),
        ]
    ).partial(options=str(options), members=", ".join(members))

    # create the chain
    supervisor_chain = (
        prompt
        | llm.bind_functions(functions=[function_def], function_call="route")
        | JsonOutputFunctionsParser()
    )
    return supervisor_chain

def summary_generator(state):
    """
    Generate a final summary of the conversation.
    Args:
        state (messages): The current state
    Returns:
         dict: The updated state with re-phrased question
    """
    # Define the prompt template
    prompt = ChatPromptTemplate(
        messages=[
            MessagesPlaceholder(variable_name="messages"),
            SystemMessage(
                content="Provide a final answer to the original question based on the entire conversation history."
            )
        ]
    )

    # LLM
    llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0, streaming=True)

    # Chain
    summary_chain = prompt | llm | StrOutputParser()

    # Run
    response = summary_chain.invoke({"messages": state["messages"]})
    return {"messages": [response]}
```

The response of either agent to the supervisor is streamed if using the `tool_calling_via_callback/st_callable_util.py` code, and also streamed as output of the summary chain.

**Comment by nick-youngblut** [comment]
For now, I'm just using the following to skip the streaming of the agent response:

```python
def get_streamlit_cb(parent_container: DeltaGenerator, members: List[str]) -> BaseCallbackHandler:
    """
    Creates a Streamlit callback handler that updates the provided Streamlit container with new tokens.
    Args:
        parent_container (DeltaGenerator): The Streamlit container where the text will be rendered.
    Returns:
        BaseCallbackHandler: An instance of a callback handler configured for Streamlit.
    """

    # Define a custom callback handler class for managing and displaying stream events in Streamlit
    class StreamHandler(BaseCallbackHandler):
        """
        Custom callback handler for Streamlit that updates a Streamlit container with new tokens.
        """

        def __init__(self, container: st.delta_generator.DeltaGenerator, initial_text: str = ""):
            """
            Initializes the StreamHandler with a Streamlit container and optional initial text.
            Args:
                container (st.delta_generator.DeltaGenerator): The Streamlit container where text will be rendered.
                initial_text (str): Optional initial text to start with in the container.
            """
            self.container = container  # The Streamlit container to update
            self.thoughts_placeholder = self.container.container()  # container to hold tool_call renders
            self.tool_output_placeholder = None # placeholder for the output of the tool call to be in the expander
            self.token_placeholder = self.container.empty()  # for token streaming
            self.text = initial_text  # The text content to display, starting with initial text
            self.agent_finished = False

        def on_agent_finish(self, finish_result: dict, **kwargs):
            """
            Called when the agent finishes.
            """
            self.agent_finished = True

        def on_llm_new_token(self, token: str, **kwargs):
            """
            Callback method triggered when a new token is received (e.g., from a language model).
            """
            if self.agent_finished:
                self.text += token
                self.token_placeholder.write(self.text)
```

**Comment by shiv248** [comment]
hey @nick-youngblut 
thanks for providing your graph and some more info.

I checked out the issue, and I can see where it is. Based on the current provided graph, it is being implemented using the AgentExecutor workflow, which is currently being phased out for the [LangGraph approach](https://python.langchain.com/docs/how_to/migrate_agent/) (LangGraph + create_react_agent). Might want to look into that approach before AgentExecutor becomes deprecated. that's why `on_agent` key value is being triggered as AgentExecutor emmits that event. With create_react_agent we can still make the dynamic subgraph agent. From my quick test it _seems_ not to be picked up within streaming, and if you want to stream the subgraph you can look at astream_events handler and have `subgraph=True`, [ref](https://langchain-ai.github.io/langgraph/how-tos/streaming-subgraphs/).

the fix you currently have will work and makes sense as well, given the `on_agent` will still be emitted (using AgentExecutor). However, I wonder if there are multiple agents if it doesn't stream for the first agent but streams for the other agents along with the supervisor?

**Comment by nick-youngblut** [comment]
Thanks @shiv248 for looking into the issue! Also, thanks for creating such a helpful resource 💪 

I've been meaning to update my langgraph code, and now I have even more motivation! 

> From my quick test it seems not to be picked up within streaming

That's great to hear. Thanks for testing it.

> However, I wonder if there are multiple agents if it doesn't stream for the first agent but streams for the other agents along with the supervisor?

That's a good question. It's a very simple hack. I'll update my langgraph code so I can abandon this approach.

**Comment by shiv248** [comment]
@nick-youngblut yea of course! After I figured out a lot of the hurdles I was like why keep it to myself? I'll make it easy to follow with high modularity and share it with the world :).

I would say that your current approach is very doable, might need to do some double-checking about the multi-agent streaming, due to the bool flag in init -> on_agent_finish staying True after first agent. if you don't face that issue then the way you have it still works for the time being.

Though if you want to migrate towards the LangGraphy approach definitely look into the [create_react_agent](https://langchain-ai.github.io/langgraph/reference/prebuilt/#langgraph.prebuilt.chat_agent_executor.create_react_agent) API for your agents in the supervisor/agents workflow, like [this](https://github.com/langchain-ai/langchain-academy/blob/main/module-4/research-assistant.ipynb) LangGraph example. And also take a look into [astream_events](https://python.langchain.com/docs/how_to/streaming/#using-stream-events) I believe they don't stream sub-graphs out of the box until you explicitly invoke [condition](https://langchain-ai.github.io/langgraph/how-tos/streaming-subgraphs/#stream-normally:~:text=Stream%20subgraph-,To%20show%20the%20updates,-occurring%20inside%20of). From the first link of this issue I think you're working with [callbacks](https://python.langchain.com/docs/concepts/#callbacks) which is totally fine as well, just worth mentioning to check out alternatives to same output/approach.

**Comment by nick-youngblut** [comment]
I've modified my supervisor-agent graph a bit, but it's mainly the same. I've noticed that after the supervisor calls a sub-agent, tools calls are not show in Streamlit for subsequent sub-agent calls from the supervisor. Have you noticed that with your tool_calling_via_callback code? Maybe it's just something with my setup.

**Comment by nick-youngblut** [comment]
It would also be helpful if Streamlit dialog showed the agent + sub-agent status (e.g., Calling Sub-agent A, Sub-agent A calling Tool X; calling Sub-agent B, sub-agent B calling Tool Y),  instead of just the tool calls and final streaming output, but maybe that's a bit too complicated for callbacks.

**Comment by leonardozilli** [comment]
> It would also be helpful if Streamlit dialog showed the agent + sub-agent status (e.g., Calling Sub-agent A, Sub-agent A calling Tool X; calling Sub-agent B, sub-agent B calling Tool Y), instead of just the tool calls and final streaming output, but maybe that's a bit too complicated for callbacks.

I would also be really interested in this! Does anyone have a lead on how to tackle this?
